'use client'

import { useTranslations } from 'next-intl'
import CreateProjectPage from '@/features/kanban/ui/CreateProjectPage'

export default function NewProjectPage() {
  const t = useTranslations('createProject')

  return (
    <CreateProjectPage
      texts={{
        nameRequired: t('nameRequired'),
        repoRequired: t('repoRequired'),
        swarmRequired: t('swarmRequired'),
        createFailed: t('createFailed'),
        createFailedCheckConsole: t('createFailedCheckConsole'),
        back: t('back'),
        title: t('title'),
        projectName: t('projectName'),
        projectNamePlaceholder: t('projectNamePlaceholder'),
        projectDescription: t('projectDescription'),
        projectDescriptionPlaceholder: t('projectDescriptionPlaceholder'),
        gitRepo: t('gitRepo'),
        gitRepoPlaceholder: t('gitRepoPlaceholder'),
        repoHint: t('repoHint'),
        defaultSwarm: t('defaultSwarm'),
        availableSwarms: t('availableSwarms'),
        swarmCapabilities: t('swarmCapabilities'),
        capabilityHint: t('capabilityHint'),
        capabilityAgentConfig: t('capabilityAgentConfig'),
        capabilitySkills: t('capabilitySkills'),
        capabilityRules: t('capabilityRules'),
        capabilityTemplate: t('capabilityTemplate'),
        capabilityTemplateSwitch: t('capabilityTemplateSwitch'),
        capabilityTemplateRepo: t('capabilityTemplateRepo'),
        capabilityTemplateBranch: t('capabilityTemplateBranch'),
        capabilityTemplateRepoPlaceholder: t('capabilityTemplateRepoPlaceholder'),
        capabilityTemplateBranchPlaceholder: t('capabilityTemplateBranchPlaceholder'),
        capabilityAgentConfigOhMy: t('capabilityAgentConfigOhMy'),
        capabilityAgentConfigOpencode: t('capabilityAgentConfigOpencode'),
        capabilityRulesClaude: t('capabilityRulesClaude'),
        capabilityRulesAgents: t('capabilityRulesAgents'),
        effectivePlanTitle: t('effectivePlanTitle'),
        effectivePlanHint: t('effectivePlanHint'),
        effectivePlanWillWriteFiles: t('effectivePlanWillWriteFiles'),
        effectivePlanWillCreateDirs: t('effectivePlanWillCreateDirs'),
        effectivePlanWillSyncSkills: t('effectivePlanWillSyncSkills'),
        effectivePlanTemplateSource: t('effectivePlanTemplateSource'),
        effectivePlanDisabled: t('effectivePlanDisabled'),
        effectivePlanNone: t('effectivePlanNone'),
        effectivePlanMoreItems: t('effectivePlanMoreItems'),
        effectivePlanTemplateUnsupported: t('effectivePlanTemplateUnsupported'),
        skillsHubCheckFailed: t('skillsHubCheckFailed'),
        missingSkillsTitle: t('missingSkillsTitle'),
        missingSkillsHint: t('missingSkillsHint'),
        missingSkillsGoSettings: t('missingSkillsGoSettings'),
        missingSkillsBeforeCreate: t('missingSkillsBeforeCreate'),
        missingSkillsAndMore: t('missingSkillsAndMore'),
        skillsHubChecking: t('skillsHubChecking'),
        skillsHubReadyPrefix: t('skillsHubReadyPrefix'),
        skillsSyncMissingAfterCreate: t('skillsSyncMissingAfterCreate'),
        addSkills: t('addSkills'),
        refreshHubSkills: t('refreshHubSkills'),
        templateSkillsCountLabel: t('templateSkillsCountLabel'),
        projectSkillsCountLabel: t('projectSkillsCountLabel'),
        hubSkillsCountLabel: t('hubSkillsCountLabel'),
        selectedProjectSkillsTitle: t('selectedProjectSkillsTitle'),
        noSelectedProjectSkills: t('noSelectedProjectSkills'),
        noHubSkills: t('noHubSkills'),
        addSelectedFromHub: t('addSelectedFromHub'),
        noHubSkillsSelected: t('noHubSkillsSelected'),
        templateSkillTag: t('templateSkillTag'),
        loadingSwarms: t('loadingSwarms'),
        swarmGroupOfficial: t('swarmGroupOfficial'),
        swarmGroupCustom: t('swarmGroupCustom'),
        selectSwarmPlaceholder: t('selectSwarmPlaceholder'),
        swarmNotFound: t('swarmNotFound'),
        swarmNoDescription: t('swarmNoDescription'),
        noSwarms: t('noSwarms'),
        targetBranch: t('targetBranch'),
        targetBranchRequired: t('targetBranchRequired'),
        loadingBranches: t('loadingBranches'),
        selectBranchPlaceholder: t('selectBranchPlaceholder'),
        cancel: t('cancel'),
        createProject: t('createProject'),
      }}
    />
  )
}
