export const DEFAULT_OH_MY_OPENCODE = {
  agents: {
    sisyphus: {
      model: 'claude-sonnet-4-5-thinking',
      temperature: 0.7,
      skills: [
        'bash',
        'read',
        'glob',
        'grep',
        'edit',
        'write',
        'webfetch',
        'todowrite',
        'lsp_goto_definition',
        'lsp_find_references',
        'lsp_symbols',
        'lsp_diagnostics',
        'lsp_prepare_rename',
        'lsp_rename',
        'ast_grep_search',
        'ast_grep_replace',
        'session_list',
        'session_read',
        'session_search',
        'session_info',
        'background_output',
        'background_cancel',
        'call_omo_agent',
        'look_at',
        'skill_mcp',
        'slashcommand',
        'interactive_bash',
        'chrome_devtools_click',
        'chrome_devtools_close_page',
        'chrome_devtools_drag',
        'chrome_devtools_emulate',
        'chrome_devtools_evaluate_script',
        'chrome_devtools_fill',
        'chrome_devtools_fill_form',
        'chrome_devtools_get_console_message',
        'chrome_devtools_get_network_request',
        'chrome_devtools_handle_dialog',
        'chrome_devtools_hover',
        'chrome_devtools_list_console_messages',
        'chrome_devtools_list_network_requests',
        'chrome_devtools_list_pages',
        'chrome_devtools_navigate_page',
        'chrome_devtools_new_page',
        'chrome_devtools_performance_analyze_insight',
        'chrome_devtools_performance_start_trace',
        'chrome_devtools_performance_stop_trace',
        'chrome_devtools_press_key',
        'chrome_devtools_resize_page',
        'chrome_devtools_select_page',
        'chrome_devtools_take_screenshot',
        'chrome_devtools_take_snapshot',
        'chrome_devtools_upload_file',
        'chrome_devtools_wait_for',
        'deepwiki_read_wiki_structure',
        'deepwiki_read_wiki_contents',
        'deepwiki_ask_question',
        'exa_web_search_exa',
        'exa_company_research_exa',
        'exa_get_code_context_exa',
        'websearch_web_search_exa',
        'stitch_create_project',
        'stitch_get_project',
        'stitch_list_projects',
        'stitch_list_screens',
        'stitch_get_screen',
        'stitch_generate_screen_from_text',
        'stitch_edit_screens',
        'stitch_generate_variants',
        'context7_resolve_library_id',
        'context7_query_docs',
        'grep_app_searchGitHub'
      ],
    },
    hephaestus: {
      model: 'claude-sonnet-4-5-thinking',
      temperature: 0.5,
      skills: [
        'bash',
        'read',
        'glob',
        'grep',
        'edit',
        'write',
        'webfetch',
        'todowrite',
        'lsp_goto_definition',
        'lsp_find_references',
        'lsp_symbols',
        'lsp_diagnostics',
        'lsp_prepare_rename',
        'lsp_rename',
        'ast_grep_search',
        'ast_grep_replace',
        'session_list',
        'session_read',
        'session_search',
        'session_info',
        'background_output',
        'background_cancel',
        'call_omo_agent',
        'look_at',
        'skill_mcp',
        'slashcommand',
        'interactive_bash',
        'chrome_devtools_click',
        'chrome_devtools_close_page',
        'chrome_devtools_drag',
        'chrome_devtools_emulate',
        'chrome_devtools_evaluate_script',
        'chrome_devtools_fill',
        'chrome_devtools_fill_form',
        'chrome_devtools_get_console_message',
        'chrome_devtools_get_network_request',
        'chrome_devtools_handle_dialog',
        'chrome_devtools_hover',
        'chrome_devtools_list_console_messages',
        'chrome_devtools_list_network_requests',
        'chrome_devtools_list_pages',
        'chrome_devtools_navigate_page',
        'chrome_devtools_new_page',
        'chrome_devtools_performance_analyze_insight',
        'chrome_devtools_performance_start_trace',
        'chrome_devtools_performance_stop_trace',
        'chrome_devtools_press_key',
        'chrome_devtools_resize_page',
        'chrome_devtools_select_page',
        'chrome_devtools_take_screenshot',
        'chrome_devtools_take_snapshot',
        'chrome_devtools_upload_file',
        'chrome_devtools_wait_for',
        'deepwiki_read_wiki_structure',
        'deepwiki_read_wiki_contents',
        'deepwiki_ask_question',
        'exa_web_search_exa',
        'exa_company_research_exa',
        'exa_get_code_context_exa',
        'websearch_web_search_exa',
        'stitch_create_project',
        'stitch_get_project',
        'stitch_list_projects',
        'stitch_list_screens',
        'stitch_get_screen',
        'stitch_generate_screen_from_text',
        'stitch_edit_screens',
        'stitch_generate_variants',
        'context7_resolve_library_id',
        'context7_query_docs',
        'grep_app_searchGitHub'
      ],
    },
    atlas: {
      model: 'claude-sonnet-4-5-thinking',
      temperature: 0.3,
      skills: [
        'bash',
        'read',
        'glob',
        'grep',
        'webfetch',
        'todowrite',
        'lsp_goto_definition',
        'lsp_find_references',
        'lsp_symbols',
        'lsp_diagnostics',
        'ast_grep_search',
        'session_list',
        'session_read',
        'session_search',
        'session_info',
        'background_output',
        'background_cancel',
        'call_omo_agent',
        'look_at',
        'skill_mcp',
        'slashcommand',
        'deepwiki_read_wiki_structure',
        'deepwiki_read_wiki_contents',
        'deepwiki_ask_question',
        'exa_web_search_exa',
        'exa_company_research_exa',
        'exa_get_code_context_exa',
        'websearch_web_search_exa',
        'stitch_get_project',
        'stitch_list_projects',
        'stitch_list_screens',
        'stitch_get_screen',
        'context7_resolve_library_id',
        'context7_query_docs',
        'grep_app_searchGitHub'
      ],
    },
  },
}

export const DEFAULT_OH_MY_OPENCODE_TEMPLATE = {
  default_run_agent: 'sisyphus',
  agents: {
    sisyphus: {
      model: 'claude-sonnet-4-5-thinking',
      temperature: 0.7,
      skills: ['react', 'tailwind', 'typescript'],
    },
    explore: {
      model: 'opencode/minimax-m2.1-free',
      temperature: 0.3,
      skills: ['read', 'glob', 'grep'],
    },
  },
  skills: ['react-skill', 'tailwind-setup'],
}

export const DEFAULT_OPENCODE_CONFIG = {
  mcp: {
    servers: {
      playwright: {
        type: 'remote',
        url: 'http://localhost:7777',
        enabled: true,
      },
      'vite-dev': {
        type: 'remote',
        url: 'http://localhost:5173',
        enabled: true,
      },
    },
  },
}
